<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */
require_once('Election.class.php');

class Bureau {
	public $listeElections = array() ;
	private  $numBureau;
	private  $ville;
	private  $libelle;

	public final  function __construct() {
	}


	// setters / getters


	public function set_numBureau($value) {
		$this->numBureau = $value;
	}

	public function get_numBureau() {
		return $this->numBureau;
	}


	public function set_ville($value) {
		$this->ville = $value;
	}

	public function get_ville() {
		return $this->ville;
	}


	public function set_libelle($value) {
		$this->libelle = $value;
	}

	public function get_libelle() {
		return $this->libelle;
	}


}
?>