<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Personne
 */
require_once('Personne.class.php');
require_once('Bureau.class.php');

class Electeur extends Personne {
	public $listeElecteurs = NULL ;
	private  $idElecteur;
	private  $identifiant;
	private  $motDePasse;
	private  $dateDeNaissance;

	public final  function __construct($idPersonne,$nom,$prenom,$adresse,
			$idElecteur,$identifiant,$motDePasse,$dateDeNaissance) {
		parent::__construct($idPersonne, $nom, $prenom, $adresse);
		$this->idElecteur=$idElecteur;
		$this->identifiant=$identifiant;
		$this->motDePasse=$motDePasse;
		$this->dateDeNaissance=$dateDeNaissance;
	}


	// setters / getters


	public function set_idElecteur($value) {
		$this->idElecteur = $value;
	}

	public function get_idElecteur() {
		return $this->idElecteur;
	}


	public function set_identifiant($value) {
		$this->identifiant = $value;
	}

	public function get_identifiant() {
		return $this->identifiant;
	}


	public function set_motDePasse($value) {
		$this->motDePasse = $value;
	}

	public function get_motDePasse() {
		return $this->motDePasse;
	}


	public function set_dateDeNaissance($value) {
		$this->dateDeNaissance = $value;
	}

	public function get_dateDeNaissance() {
		return $this->dateDeNaissance;
	}


}
?>