<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */
require_once('Bureau.class.php');

class Election {
	public $listeBureaux = array() ;
	private  $idElection;
	private  $nom;
	private  $type;
	private  $dateElection;

	public final  function __construct($idElection, $nom, $type, $dateElection) {
		$this->idElection=$idElection;
		$this->nom=$nom;
		$this->type=$type;
		$this->dateElection=$dateElection;
	}


	// setters / getters


	public function set_idElection($value) {
		$this->idElection = $value;
	}

	public function get_idElection() {
		return $this->idElection;
	}


	public function set_nom($value) {
		$this->nom = $value;
	}

	public function get_nom() {
		return $this->nom;
	}


	public function set_type($value) {
		$this->type = $value;
	}

	public function get_type() {
		return $this->type;
	}


	public function set_dateElection($value) {
		$this->dateElection = $value;
	}

	public function get_dateElection() {
		return $this->dateElection;
	}


}
?>