<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Personne {
	private  $idPersonne;
	private  $nom;
	private  $prenom;
	private  $adresse;

	public function __construct($idPersonne,$nom,$prenom,$adresse) {
		$this->nom=$nom;
		$this->idPersonne=$idPersonne;
		$this->prenom=$prenom;
		$this->adresse=$adresse;
	}
	// setters / getters

	public function set_idPersonne($value) {
		$this->idPersonne = $value;
	}
	public function get_idPersonne() {
		return $this->idPersonne;
	}
	public function set_nom($value) {
		$this->nom = $value;
	}
	public function get_nom() {
		return $this->nom;
	}
	public function set_prenom($value) {
		$this->prenom = $value;
	}
	public function get_prenom() {
		return $this->prenom;
	}
	public function set_adresse($value) {
		$this->adresse = $value;
	}
	public function get_adresse() {
		return $this->adresse;
	}
}
?>