<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */
require_once('Electeur.class.php');
require_once('Candidat.class.php');
require_once('Election.class.php');

class votePour {
	private  $signature;


	// setters / getters


	public function set_signature($value) {
		$this->signature = $value;
	}

	public function get_signature() {
		return $this->signature;
	}


}
?>